language: ruby

os: linux

dist: bionic
sudo: required

rvm:
- ruby-head
- 2.7
- 2.6
- 2.5
- 2.4

env:
  global:
  - PYCALL_DEBUG_FIND_LIBPYTHON=1
  matrix:
  - PYENV_VERSION=3.8.0
  - PYENV_VERSION=3.7.5
  - PYENV_VERSION=2.7.17
  - PYENV_VERSION=system LIBPYTHON=/usr/lib/x86_64-linux-gnu/libpython3.6m.so
  - PYENV_VERSION=system LIBPYTHON=/usr/lib/x86_64-linux-gnu/libpython2.7.so
  - PYENV_VERSION=miniconda2-4.3.30
  - PYENV_VERSION=miniconda3-4.3.30

matrix:
  include:
  - os: osx
    osx_image: xcode11.2
    compiler: clang
    rvm: 2.7
    env: PYENV_VERSION=3.8.0
  - os: osx
    osx_image: xcode11.2
    compiler: clang
    rvm: 2.6
    env: PYENV_VERSION=3.8.0
  - os: osx
    osx_image: xcode11.2
    compiler: clang
    rvm: 2.5
    env: PYENV_VERSION=3.8.0
  - os: osx
    osx_image: xcode11.2
    compiler: clang
    rvm: 2.4
    env: PYENV_VERSION=3.8.0
  - os: osx
    osx_image: xcode11.2
    compiler: clang
    rvm: 2.7
    env: PYENV_VERSION=miniconda3-4.3.11
  - os: osx
    osx_image: xcode11.2
    compiler: clang
    rvm: 2.6
    env: PYENV_VERSION=miniconda3-4.3.11
  - os: osx
    osx_image: xcode11.2
    compiler: clang
    rvm: 2.5
    env: PYENV_VERSION=miniconda3-4.3.11
  - os: osx
    osx_image: xcode11.2
    compiler: clang
    rvm: 2.4
    env: PYENV_VERSION=miniconda3-4.3.11
  allow_failures:
  - os: osx

before_install:
- export PATH="$(pyenv root)/bin:$PATH"
- eval "$(pyenv init -)"

install:
- ci/travis_install.sh

before_script:
- . ci/travis_before_script.sh
- bundle exec rake clobber compile
- python lib/pycall/python/investigator.py
